locale                   : "en"
title                    : "SITC"
title_separator          : "-"
name                     : "SITC"
description              : "DWB's Jekyll Website."
url                      : "https://walkwithweb.com"
baseurl                  : ""
repository               : "walkwithweb/walkwithweb.github.io"